dtx:
  mysqlds:
    uniqueResourceName: mysqlXA
    xaDataSourceClassName: com.mysql.cj.jdbc.MysqlXADataSource
    xaProperties:
      URL: jdbc:mysql:///ntsp612db
      databaseName: ntsp612db
      password: root
      user: root
  orads:
    uniqueResourceName: oraXA
    xaDataSourceClassName: oracle.jdbc.xa.client.OracleXADataSource
    xaProperties:
      URL: jdbc:oracle:thin:@localhost:1521:xe
      databaseName: xe
      password: manager
      user: system
spring:
  aop:
    proxy-target-class: false
